# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{netz}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shawn Anderson"]
  s.date = %q{2010-10-27}
  s.description = %q{P2P Networking library for us in games. }
  s.email = %q{shawn42@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/netz.rb",
     "lib/netz/broadcaster.rb",
     "lib/netz/catcher.rb",
     "lib/netz/client.rb",
     "lib/netz/command.rb",
     "lib/netz/command_serializer.rb",
     "lib/netz/safe_array.rb",
     "netz.gemspec",
     "script/run_client.rb",
     "script/run_lobby.rb"
  ]
  s.homepage = %q{http://shawn42.github.com/netz}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{netz}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Networking library for use in games.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<gosu>, [">= 0"])
      s.add_runtime_dependency(%q<bundler>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<gosu>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<gosu>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
  end
end

